# Generated by Django 4.0.1 on 2022-02-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoadImage',
            new_name='PrimerTabla',
        ),
    ]
